baseURL = "https://minvws.github.io/nl-rdo-manon/"
title = "Manon"

[menu]

[[menu.main]]
name = "Docs"
url = "docs"
weight = 10

[languages]

[languages.nl]
languageName = "Nederlands"
weight = 1

[languages.en]
languageName = "English"
weight = 2

[markup.goldmark]

[markup.goldmark.parser]
autoHeadingID = false

[markup.goldmark.renderer]
unsafe = true
